lint:
  files_exist:
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
  nextflow_config:
    - params.input
  nf_test_content:
    - versions.yml
  schema_lint: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Saima Sultana Tithi
  description: This pipeline include tools for performing consistent summary count
    based rare variant burden test, which is useful when we only have sequenced cases
    data, no control data; here we can compare the cases against public summary count
    data, such as gnomAD data
  force: false
  is_nfcore: true
  name: rarevariantburden
  org: nf-core
  outdir: .
  version: 1.0.0dev
