lint: {}
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Saima Sultana Tithi
  description: This pipeline include tools for performing consistent summary count
    based rare variant burden test, which is useful when we only have sequenced cases
    data, no control data; here we can compare the cases against public summary count
    data, such as gnomAD data
  force: false
  is_nfcore: true
  name: rarevariantburden
  org: nf-core
  outdir: .
  version: 1.0.0dev
